spring.application.name=price

# Config inicial para H2 en Memoria
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:price
spring.datasource.username=user
spring.datasource.password=user
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# para crear e inicializar la tabla ( Prices )
spring.jpa.defer-datasource-initialization=true

# para habilitar la consola en el nav web via http
spring.h2.console.enabled=true